name: citra-build

on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
  pull_request:
    branches: [ master ]

permissions:
  id-token: write
  contents: read
  attestations: write

jobs:
  windows:
    strategy:
      fail-fast: false
      matrix:
        include:
        - target: mxe
          os: ubuntu-latest
          container:
            image: opensauce04/azahar-build-environment:latest
            options: -u 1001
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    defaults:
      run:
        shell: 'bash'
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPILERCHECK: content
      CCACHE_SLOPPINESS: time_macros
      CACHE_ENABLED: ${{ github.ref_type != 'tag' }}
      OS: windows
      TARGET: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Set up cache
        if: ${{ env.CACHE_ENABLED == 'true' }}
        uses: actions/cache@v5
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-${{ matrix.target }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-
      - name: Set up MSVC
        if: ${{ matrix.target == 'msvc' }}
        uses: azahar-emu/msvc-dev-cmd@v1
      - name: Install tools (MSVC)
        if: ${{ matrix.target == 'msvc' }}
        run: |
          choco install ccache ninja ptime wget
      - name: Checkout vcpkg for FFmpeg 7.1.2 (MSVC)
        if: ${{ matrix.target == 'msvc' }}
        shell: pwsh
        run: |
          cd C:\vcpkg
          git checkout 5087d22fd76fe1844ca492866055dea3c34e7f52
          .\bootstrap-vcpkg.bat -disableMetrics
      - name: Build FFmpeg (MSVC)
        if: ${{ matrix.target == 'msvc' }}
        run: vcpkg install
          ffmpeg[avcodec,avfilter,avformat,swresample,aom,dav1d,mp3lame,opus,snappy,soxr,theora,vorbis,vpx,vulkan,x264,x265]:x64-windows-release
      - name: Install vulkan-sdk (MSVC)
        if: ${{ matrix.target == 'msvc' }}
        run: |
          wget https://sdk.lunarg.com/sdk/download/1.4.304.1/windows/VulkanSDK-1.4.304.1-Installer.exe -O D:/a/_temp/vulkan.exe
          D:/a/_temp/vulkan.exe --accept-licenses --default-answer --confirm-command install
      - name: Install NSIS (MSVC)
        if: ${{ github.ref_type == 'tag' && matrix.target == 'msvc' }}
        run: |
          wget https://download.sourceforge.net/project/nsis/NSIS%203/3.11/nsis-3.11-setup.exe -O D:/a/_temp/nsis-setup.exe
          ptime D:/a/_temp/nsis-setup.exe /S
        shell: pwsh
      - name: Disable line ending translation
        run: git config --global core.autocrlf input
      - name: Build (MSVC)
        if: ${{ matrix.target == 'msvc' }}
        run: ./.ci/win-msvc.sh
      - name: Build (MXE)
        if: ${{ matrix.target == 'mxe' }}
        run: ./.ci/win-mxe.sh
      - name: Generate installer (MSVC)
        if: ${{ github.ref_type == 'tag' && matrix.target == 'msvc' }}
        run: |
          cd src\installer
          "C:\Program Files (x86)\NSIS\makensis.exe" /DPRODUCT_VARIANT=${{ matrix.target }} /DPRODUCT_VERSION=${{ github.ref_name }} citra.nsi
          mkdir ..\..\artifacts 2> NUL
          move /y *.exe ..\..\artifacts\
        shell: cmd
      - name: Generate installer (MXE)
        if: ${{ github.ref_type == 'tag' && matrix.target == 'mxe' }}
        run: |
          export PATH="/opt/mxe/usr/bin:${PATH}" # TODO: Why do we have to do this if it's in the image?
          cd src/installer
          x86_64-w64-mingw32.shared-makensis -DPRODUCT_VARIANT=${{ matrix.target }} -DPRODUCT_VERSION=${{ github.ref_name }} citra.nsi
          mkdir -p ../../artifacts
          mv ./*.exe ../../artifacts/
      - name: Pack
        run: ./.ci/pack.sh
      - name: Generate SBOM
        if: ${{ github.ref_type == 'tag' }}
        uses: anchore/sbom-action@v0
        with:
          path: build/
          format: spdx-json
          output-file: artifacts/windows-${{ matrix.target }}.spdx.json
          upload-artifact: false
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.OS }}-${{ env.TARGET }}
          path: artifacts/
      - name: Attest artifacts
        if: ${{ github.ref_type == 'tag' }}
        uses: actions/attest@v4
        with:
          subject-path: |
            artifacts/*.zip
            artifacts/*.exe
          sbom-path: artifacts/windows-${{ matrix.target }}.spdx.json
